# Generated by Django 3.0.8 on 2020-07-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200720_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(max_length=50),
        ),
    ]
