# Generated by Django 3.0.8 on 2020-07-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200721_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favour',
            name='length',
        ),
    ]
