# Generated by Django 3.0.8 on 2020-07-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
