# Generated by Django 3.0.8 on 2020-07-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='students',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(default='нет группы', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.ManyToManyField(to='pages.Interest'),
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
