# Generated by Django 3.0.8 on 2020-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200724_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['counter']},
        ),
        migrations.AddField(
            model_name='interest',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
